[package]
name = "surge-ping"
version = "0.4.0"
authors = ["kolapapa <kolapapa2021@gmail.com>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/kolapapa/surge-ping"
repository = "https://github.com/kolapapa/surge-ping"
description = "Asynchronous ICMP ping library"
keywords = ["tokio", "icmp", "ping"]
categories = ["network-programming", "asynchronous"]

[dependencies]
log = "0.4.14"
parking_lot = "0.11.2"
pnet_packet = "0.29.0"
rand = "0.8.4"
socket2 = { version = "0.4.2", features = ["all"] }
thiserror = "1.0.30"
tokio = { version = "1.15.0", features = ["time", "macros"] }

[dev-dependencies]
log = "0.4.14"
structopt = "0.3.25"
pretty_env_logger = "0.4.0"
tokio = { version = "1.15.0", features = ["full"] }
futures = "0.3.19"

[[example]]
name = "simple"

[[example]]
name = "cmd"

[[example]]
name = "multi_ping"
